from leetcode.problems import p17

test_cases = [
    ("23", ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"]),
    ("", []),
    ("2", ["a", "b", "c"]),
    (
        "5467",
        [
            "jgmp",
            "jgmq",
            "jgmr",
            "jgms",
            "jgnp",
            "jgnq",
            "jgnr",
            "jgns",
            "jgop",
            "jgoq",
            "jgor",
            "jgos",
            "jhmp",
            "jhmq",
            "jhmr",
            "jhms",
            "jhnp",
            "jhnq",
            "jhnr",
            "jhns",
            "jhop",
            "jhoq",
            "jhor",
            "jhos",
            "jimp",
            "jimq",
            "jimr",
            "jims",
            "jinp",
            "jinq",
            "jinr",
            "jins",
            "jiop",
            "jioq",
            "jior",
            "jios",
            "kgmp",
            "kgmq",
            "kgmr",
            "kgms",
            "kgnp",
            "kgnq",
            "kgnr",
            "kgns",
            "kgop",
            "kgoq",
            "kgor",
            "kgos",
            "khmp",
            "khmq",
            "khmr",
            "khms",
            "khnp",
            "khnq",
            "khnr",
            "khns",
            "khop",
            "khoq",
            "khor",
            "khos",
            "kimp",
            "kimq",
            "kimr",
            "kims",
            "kinp",
            "kinq",
            "kinr",
            "kins",
            "kiop",
            "kioq",
            "kior",
            "kios",
            "lgmp",
            "lgmq",
            "lgmr",
            "lgms",
            "lgnp",
            "lgnq",
            "lgnr",
            "lgns",
            "lgop",
            "lgoq",
            "lgor",
            "lgos",
            "lhmp",
            "lhmq",
            "lhmr",
            "lhms",
            "lhnp",
            "lhnq",
            "lhnr",
            "lhns",
            "lhop",
            "lhoq",
            "lhor",
            "lhos",
            "limp",
            "limq",
            "limr",
            "lims",
            "linp",
            "linq",
            "linr",
            "lins",
            "liop",
            "lioq",
            "lior",
            "lios",
        ],
    ),
]


class TestP1:
    def test_p17_1(self):
        case = test_cases[0]
        assert p17.Solution().letterCombinations(case[0]) == case[1]

    def test_p17_2(self):
        case = test_cases[1]
        assert p17.Solution().letterCombinations(case[0]) == case[1]

    def test_p17_3(self):
        case = test_cases[2]
        assert p17.Solution().letterCombinations(case[0]) == case[1]

    def test_p17_4(self):
        case = test_cases[3]
        assert p17.Solution().letterCombinations(case[0]) == case[1]
